// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1748285350);
user_pref("app.update.lastUpdateTime.background-update-timer", 1748285350);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1748285350);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1748285319);
user_pref("browser.laterrun.bookkeeping.sessionCount", 1);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.startup.homepage_override.buildID", "20240418052210");
user_pref("browser.startup.homepage_override.mstone", "115.10.0");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.lastAppBuildId", "20250315233106");
user_pref("extensions.lastAppVersion", "7.0.15");
user_pref("extensions.lastPlatformVersion", "115.10.0");
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.webextensions.uuids", "{\"better-bibtex@iris-advies.com\":\"080aa77d-f3cc-4fc4-8313-e844d9e587b8\",\"zoteroAddons@ytshen.com\":\"0ca0d2ca-f67e-4f27-8103-e1923f5fcf40\",\"zoterostyle@polygon.org\":\"1501bc36-a038-44d2-b897-c86612447157\",\"zotmoov@wileyy.com\":\"cfd1a221-24a7-41a0-9a6d-dc306806c3db\"}");
user_pref("extensions.zotero.Zotero.AddonItem.key", "8NL6WMFP");
user_pref("extensions.zotero.attachmentRenameTemplate", "@{{ if {{ authorsCount > 2 }} }}\n{{ authors max=\"1\" suffix=\" et al\" }}\n{{ else }}\n{{ authors join=\"_\" }}\n{{ endif }}\n_{{ year }}");
user_pref("extensions.zotero.dataDir", "/Users/test/Zotero user");
user_pref("extensions.zotero.downloadAssociatedFiles", false);
user_pref("extensions.zotero.firstRun.skipFirefoxProfileAccessCheck", true);
user_pref("extensions.zotero.firstRun2", false);
user_pref("extensions.zotero.httpServer.localAPI.enabled", true);
user_pref("extensions.zotero.lastSelectedPrefPane", "zotero-prefpane-general");
user_pref("extensions.zotero.lastViewedFolder", "L1");
user_pref("extensions.zotero.panes.abstract.open", true);
user_pref("extensions.zotero.panes.attachment-annotations.open", true);
user_pref("extensions.zotero.panes.attachment-info.open", true);
user_pref("extensions.zotero.panes.attachments.open", true);
user_pref("extensions.zotero.panes.info.open", true);
user_pref("extensions.zotero.panes.libraries-collections.open", true);
user_pref("extensions.zotero.panes.notes.open", true);
user_pref("extensions.zotero.panes.related.open", true);
user_pref("extensions.zotero.panes.tags.open", true);
user_pref("extensions.zotero.prefVersion", 13);
user_pref("extensions.zotero.sourceList.persist", "{\"L1\":true,\"P1\":false}");
user_pref("extensions.zotero.translators.better-bibtex.citekeyFormat", "authEtal2(sep = \"_\").lower + \"_\" + year");
user_pref("extensions.zotero.translators.better-bibtex.citekeyFormatEditing", "authEtal2(sep=\"_\").lower + \"_\" + year");
user_pref("extensions.zotero.translators.better-bibtex.path.git", "/opt/homebrew/bin/git");
user_pref("extensions.zotero.translators.better-bibtex.path.texstudio", "");
user_pref("extensions.zotero.translators.better-bibtex.platform", "mac");
user_pref("extensions.zotero.useDataDir", true);
user_pref("extensions.zotero.zoteroaddons.firstInstalledVersion", "2.1.1");
user_pref("extensions.zotero.zoteroaddons.guideStatus", 1);
user_pref("extensions.zotero.zoterostyle.annotationColors", "[[\"green\",\"#5fb236\"],[\"yellow\",\"#ffd400\"],[\"red\",\"#ff6666\"],[\"🧠_Term\",\"#f19837\"],[\"👤_Person\",\"#a28ae5\"],[\"📄_Document\",\"#2ea8e5\"],[\"🎟️_Event\",\"#e56eee\"],[\"🗃️_Group\",\"#3f51b5\"],[\"#_Part\",\"#000000\"],[\"#_Chapter\",\"#404040\"],[\"#_Index\",\"#aaaaaa\"]]");
user_pref("extensions.zotero.zoterostyle.annotationColorsGroups", "[[\"Obsidian Markup\",[[\"green\",\"#5fb236\"],[\"yellow\",\"#ffd400\"],[\"red\",\"#ff6666\"],[\"🧠_Term\",\"#f19837\"],[\"👤_Person\",\"#a28ae5\"],[\"📄_Document\",\"#2ea8e5\"],[\"🎟️_Event\",\"#e56eee\"],[\"🗃️_Group\",\"#3f51b5\"],[\"#_Part\",\"#000000\"],[\"#_Chapter\",\"#404040\"],[\"#_Index\",\"#aaaaaa\"]]]]");
user_pref("extensions.zoteroMacWordIntegration.lastAttemptedVersion", "7.0.6.SOURCE");
user_pref("extensions.zoteroOpenOfficeIntegration.lastAttemptedVersion", "7.0.1.SOURCE");
user_pref("extensions.zotmoov.file_behavior", "copy");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("intl.accept_languages", "en-US, en");
